### ISSUE TITLE
Extract Visualization library.

### ISSUE THREAD

**Issue by Aquaj** [Aquaj/osmosis#3]
- [x] Extract to a gem. 
  -  [ ] Aquaj/foliage-gem#1
  -  [ ] Aquaj/foliage-gem#2
  -  [ ] Aquaj/foliage-gem#3
  -  [ ] Aquaj/foliage-gem#4
- [ ] Replace every use of Visualization in Osmosis' code  by calls to `foliage`.
